### ISSUE TITLE
[Add] : ⚠🚨 Noticed Missing <DOCTYPE html>, Meta Tags in Number of Files in this Path Animating-Buttons\public\Buttons

### ISSUE THREAD

**Issue by NarendraKoya999** [Spyware007/Animating-Buttons#1955]
### Purpose of Raising this Issue
**1. About `Meta Tags` Importance**
Meta tags are important because they impact how your site appears in the SERPs and how many people will be inclined to click through to your website. They will therefore impact your traffic and engagement rates, which can impact your SEO and rankings. Meta tags are an important part of a solid SEO strategy. Although some tags might not have a direct impact on rankings, they do impact how your site appears within the digital ecosystem. Additionally, they could be a factor in many non-traditional search results, like Knowledge Graph, Google image search, voice, and more. No brand should neglect them when developing content.

**2. About `<DOCTYPE html>`**
All HTML need to have a DOCTYPE declared. The DOCTYPE is not actually an element or HTML tag. It lets the browser know how the document should be interpreted, by indicating what version or standard of HTML (or other markup language) is being used.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@NarendraKoya999 No need of this as backend is shifted to Firebase
